export const FIELD_AUTOCOMPLETE_FETCHING = "FIELD_AUTOCOMPLETE_FETCHING";
export const FIELD_AUTOCOMPLETE_FULFILLED = "FIELD_AUTOCOMPLETE_FULFILLED";
export const FIELD_AUTOCOMPLETE_REJECTED = "FIELD_AUTOCOMPLETE_REJECTED";
export const FIELD_AUTOCOMPLETE_NO_MATCH = "FIELD_AUTOCOMPLETE_NO_MATCH";
export const FETCH_SYSTEMBOLAGET_WINE_DATA_FULFILLED =
  "FETCH_SYSTEMBOLAGET_WINE_DATA_FULFILLED";
export const FETCH_SYSTEMBOLAGET_WINE_DATA_REJECTED =
  "FETCH_SYSTEMBOLAGET_WINE_DATA_REJECTED";
export const FETCH_SYSTEMBOLAGET_WINE_DATA_FETCHING =
  "FETCH_SYSTEMBOLAGET_WINE_DATA_FETCHING";
