export const ADD_REVIEW_FETCHING = "ADD_REVIEW_FETCHING";
export const ADD_REVIEW_FULFILLED = "ADD_REVIEW_FULFILLED";
export const ADD_REVIEW_REJECTED = "ADD_REVIEW_REJECTED";
export const SET_SNACKBAR = "SET_SNACKBAR";
export const CLEAR_SNACKBAR = "CLEAR_SNACKBAR";
export const SYSTEMBOLAGET_FETCHING = "SYSTEMBOLAGET_FETCHING";
export const SET_INITIAL_VALUES = "SET_INITIAL_VALUES";
export const CLEAR_INITIAL_VALUES = "CLEAR_INITIAL_VALUES";
export const SYSTEMBOLAGET_CLEAR_VALUES = "SYSTEMBOLAGET_CLEAR_VALUES";
export const FETCH_SYSTEMBOLAGET_FULFILLED = "FETCH_SYSTEMBOLAGET_FULFILLED";
export const FETCH_SYSTEMBOLAGET_REJECTED = "FETCH_SYSTEMBOLAGET_REJECTED";
export const FETCH_SYSTEMBOLAGET_NO_MATCH = "FETCH_SYSTEMBOLAGET_NO_MATCH";
export const FIELD_AUTOCOMPLETE_FETCHING = "FIELD_AUTOCOMPLETE_FETCHING";
export const FIELD_AUTOCOMPLETE_FULFILLED = "FIELD_AUTOCOMPLETE_FULFILLED";
export const FIELD_AUTOCOMPLETE_REJECTED = "FIELD_AUTOCOMPLETE_REJECTED";
export const FIELD_AUTOCOMPLETE_NO_MATCH = "FIELD_AUTOCOMPLETE_NO_MATCH";
export const FIELD_AUTOCOMPLETE_CLEAR_FOCUS = "FIELD_AUTOCOMPLETE_CLEAR_FOCUS";
export const FIELD_AUTOCOMPLETE_FOCUS_FIELD = "FIELD_AUTOCOMPLETE_FOCUS_FIELD";
export const FETCH_SYSTEMBOLAGET_COUNTRIES_FULFILLED =
  "FETCH_SYSTEMBOLAGET_COUNTRIES_FULFILLED";
export const FETCH_SYSTEMBOLAGET_COUNTRIES_REJECTED =
  "FETCH_SYSTEMBOLAGET_COUNTRIES_REJECTED";
export const FETCH_SYSTEMBOLAGET_COUNTRIES_FETCHING =
  "FETCH_SYSTEMBOLAGET_COUNTRIES_FETCHING";
export const FETCH_SYSTEMBOLAGET_SUBTYPES_FULFILLED =
  "FETCH_SYSTEMBOLAGET_SUBTYPES_FULFILLED";
export const FETCH_SYSTEMBOLAGET_SUBTYPES_REJECTED =
  "FETCH_SYSTEMBOLAGET_SUBTYPES_REJECTED";
export const FETCH_SYSTEMBOLAGET_SUBTYPES_FETCHING =
  "FETCH_SYSTEMBOLAGET_SUBTYPES_FETCHING";
export const FETCH_SYSTEMBOLAGET_TYPES_FULFILLED =
  "FETCH_SYSTEMBOLAGET_TYPES_FULFILLED";
export const FETCH_SYSTEMBOLAGET_TYPES_REJECTED =
  "FETCH_SYSTEMBOLAGET_TYPES_REJECTED";
export const FETCH_SYSTEMBOLAGET_TYPES_FETCHING =
  "FETCH_SYSTEMBOLAGET_TYPES_FETCHING";
export const FETCH_SYSTEMBOLAGET_WINE_DATA_FULFILLED =
  "FETCH_SYSTEMBOLAGET_WINE_DATA_FULFILLED";
export const FETCH_SYSTEMBOLAGET_WINE_DATA_REJECTED =
  "FETCH_SYSTEMBOLAGET_WINE_DATA_REJECTED";
export const FETCH_SYSTEMBOLAGET_WINE_DATA_FETCHING =
  "FETCH_SYSTEMBOLAGET_WINE_DATA_FETCHING";
export const FETCH_SYSTEMBOLAGET_WINE_DATA_NO_MATCH =
  "FETCH_SYSTEMBOLAGET_WINE_DATA_NO_MATCH";
export const SET_AC_PRODUCERS = "SET_AC_PRODUCERS";
export const SET_AC_NAMES = "SET_AC_NAMES";
export const SET_AC_GRAPES = "SET_AC_GRAPES";
export const SET_AC_COUNTRIES = "SET_AC_COUNTRIES";
export const RESET_ADD_REVIEW_VALUES = "RESET_ADD_REVIEW_VALUES";
export const UPDATE_ADD_REVIEW_VALUES = "UPDATE_ADD_REVIEW_VALUES";
